name: mozdev-deploy

on:
  push:
    branches:
      - main

jobs:
  build-js-css:
    name: Deploy to SERVER 

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Commit assets
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHun Action"
          git checkout -B deploy

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: 'cd /var/www/school-management && sh server_deploy.sh'


  remove-branch:
    name: remove deploy branch
    runs-on: ubuntu-latest
    needs: [build-js-css]
    if: github.ref == 'refs/heads/producao'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Reset
        run: git push origin --delete deploy
