name: Acessar servidor EC2 e clonar repositório

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar chaves SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts

    - name: Clonar repositório
      run: |
        ssh ubuntu@${{ secrets.SSH_IP }} 'git clone git@github.com:humbertonoa83/rodovia.git'
