name: mozdev-deploy

on:
  push:
    branches:
      - main

jobs:
  build-js-css:
    name: Deploy to Server 

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Commit assets
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHun Action"
          git checkout -B deploy

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$EC2_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 54.227.191.150 >> ~/.ssh/known_hosts

      - name: SSH into EC2 instance
        run: |
          ssh -i ~/.ssh/id_rsa ubunto@54.227.191.150 "/var/www/school-management/ && sh server_deploy.sh"


 
