name: make dir

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/aws.pem
          chmod 600 ~/.ssh/aws.pem
          ssh-keyscan -t rsa 54.227.191.150 >> ~/.ssh/known_hosts

      - name: Criar diretório no servidor
        run: |
          ssh -i ~/.ssh/aws.pem usuário@54.227.191.150 "mkdir /home/ubuntu/TESTE1"
