name: Create Folder
on:
  push:
    branches:
      - main

jobs:
  create-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Folder
        run: |
          sshpass -p par14 ssh samuel@54.227.191.150 'cd /var/www/mozdev-ujc-actions/ && sh server_deploy.sh'
