name: mozdev-deploy

on:
  push:
    branches:
      - main

jobs:
  build-js-css:
    name: Deploy to SERVER 

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: 'cd /var/www/school-management && sh server_deploy.sh'
